"""empty message

Revision ID: 84705be410b1
Revises: ded5da589107
Create Date: 2023-01-04 23:12:03.155838

"""

# revision identifiers, used by Alembic.
revision = '84705be410b1'
down_revision = 'ded5da589107'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
