"""empty message

Revision ID: ded5da589107
Revises: 27fb514b3f84
Create Date: 2023-01-04 23:02:49.032629

"""

# revision identifiers, used by Alembic.
revision = 'ded5da589107'
down_revision = '27fb514b3f84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
